c
c    this code evaluates the pdf of several quantities
c    the data are read by files that are generated by 
c    the codes in the directory CODESCH9/POST2
c    hence before should be used the codes in CODESCH9/POST2
c    which reads the fields saved as field****.dat
c    from the quantities in the fields in the file 
c    chatratu.f (routine vortur) certain fluctuating
c    quantities are evaluated at the walls and at certain
c    j locations at the cell centre. Respectively are written
c    in the files lowalpdf , upwalpdf , and quapdf***.
c
      program main 
      parameter (m1=65,m3=257,mfile=50,m2=151)
      parameter (mqua=42,mhpd=201,mqu=mqua)
      parameter (mcqu=19,mcqw=14)
      dimension qcaplv(mqua,m1*m3*mfile),quav(mqua)
      dimension qrms(mqua),qskew(mqua),qflat(mqua)
      dimension qavgv(mqua),qmapdf(mqua),qmipdf(mqua)
      dimension qmaflu(mqua),qmiflu(mqua)
      dimension allma(mqua),allmi(mqua)
      dimension frrms(4,5),frskew(4,5),frflat(4,5),quase(5),nsafr(4,5)
      dimension perfr(4),evefr(4)
      dimension qavck(4),qrmsck(4)
      common/quaprs/y2s(m2),tstppl(6,m2),sijsij(m2),enstr(m2),enpro(m2)
     1,pvp(6,m2),tostpl(6,m2),vmece(6,m2),pmece(m2),vomce(6,m2)
     1,vstp(6,m2),tstp(6,m2),skew(6,m2),flat(6,m2),dvtv(6,m2)
     1,vtv(6,m2),vvo(6,m2),hel(6,m2),dstr(6,m2),vcom(6,m2)
      common/quaprc/yp2(m2),vmepo(6,m2),vompo(6,m2)
      common/pdf1/alev(mqu,mhpd),nllc(mqu,mhpd)
      common/pdf2/ntoz(mqu),qpdf(mqu),pdfvo(mqu)
      common/pdf3/nou(mqu),npou(mqu),ntoc(mqu)
      common/pdf4/pdft(mqu)
      common/pdf5/lipdf,lipdn,lipdh
      common/npdf/nqua
      common/nn2/n2,n2m
      dimension ascma(mcqu),ascmi(mcqu),ordma(mcqu),ordmi(mcqu)
      common/cpdf1/alas(mcqu,mhpd),alor(mcqu,mhpd)
      common/cpdf2/ncpdf(mcqu,mhpd,mhpd),ntcpdf(mcqu),nocpdf(mqu)
      common/cpdf3/ncpdw(mcqw,mhpd,mhpd),ntcpdw(mcqw),nocpdw(mcqw)
      parameter (mcqul=7)
      common/cpdf1l/alaslo(mcqul,mhpd),alorlo(mcqul,mhpd)
      common/cpdf2l/ncpdfl(mcqul,mhpd,mhpd),ntcpdl(mcqul),nocpdl(mqu)
      parameter (mcqvo=9)
      common/cpdf4/nvopdf(mcqvo,mhpd,mhpd),ntcpvo(mcqvo),novopd(mcqvo)
      common/cpdf6/cpdft(mcqu),cpdfv(mcqu,mhpd,mhpd)
      common/cpdf6l/cpdftl(mcqul),cpdfvl(mcqul,mhpd,mhpd)
      common/cpdf9/cpdwt(mcqw),cpdwv(mcqw,mhpd,mhpd)
      common/cpdf8/cpdtvo(mcqvo),cpdfvo(mcqvo,mhpd,mhpd)
      dimension jprq(10)
      character*3 njpse
      character*3 pjprc
      character*60 namfile 
      open(15,file='statpdf.d')
       read(15,*) n2,scamax,time
       read(15,*) npq,(jprq(n),n=1,npq)
       read(15,*)lipdf
       read(15,*) itot
      lipdh=(lipdf-1)/2
      lipdn=(lipdf-1)
      open(18,file='pdfglob.out')
      write(18,*) ' total pdf'
       n2m=n2-1
      pi=2.*asin(1.)
      re=4200.
      write(6,*)'n2,time,re,lipdf,itot',n2,time,re,lipdf,itot
      write(18,*)'n2,time,re,lipdf,itot',n2,time,re,lipdf,itot
      qeps=.1e-03
      qmax=10.
      qcmax=qmax*0.5
      qsmax=qmax*scamax
      alqcma=2.
      alqcmi=-3.
c
c    evaluates the intervals for the pdf
c    as means abscissa or ordinate
c    these are necessary for the joint pdf
c
           do ll=1,lipdn
      alli=(ll-1+0.5)/float(lipdn)
      allh=(ll-1-lipdh+0.5)/float(lipdh)
      alaslo(1,ll)=(alqcmi+(alqcma-alqcmi)*alli)
      alorlo(1,ll)=(alqcmi+(alqcma-alqcmi)*alli)
      alas(1,ll)=qcmax*alli
      alor(1,ll)=qcmax*alli
      alas(2,ll)=qcmax*allh
      alor(2,ll)=qcmax*allh
      alas(3,ll)=qsmax*allh
      alor(3,ll)=qsmax*allh
      alas(4,ll)=allh
      alor(4,ll)=allh
           enddo
      aaaa=1.
c
c   the joint pdf output is in a file with contour plots
c   these files are written to be observed by the TURB3D package
c   here the coordinates file is given
c   
c   coordinate for joipdf between velocity and vorticity
c
      namfile='cojpdfdo.dat'
      open(26,file=namfile,form='unformatted')
      write(26)lipdn,lipdn
      write(26) ((alas(1,la),la=1,lipdn),lo=1,lipdn)
     1         ,((alor(1,lo),la=1,lipdn),lo=1,lipdn)
      close(26)
      ia=1
c   
c   coordinate for joipdf between strain rate and vorticity
c   vortex stretching terms
c
      namfile='cojpdfvs.dat'
      open(26,file=namfile,form='unformatted')
      write(26)lipdn,lipdn,ia
      write(26) ((alas(2,la),la=1,lipdn),lo=1,lipdn)
     1         ,((alor(2,lo),la=1,lipdn),lo=1,lipdn)
     1         ,((aaaa,la=1,lipdn),lo=1,lipdn)
      close(26)
      namfile='cojpdfep.dat'
      open(26,file=namfile,form='unformatted')
      write(26)lipdn,lipdn,ia
      write(26) ((alas(3,la),la=1,lipdn),lo=1,lipdn)
     1         ,((alor(3,lo),la=1,lipdn),lo=1,lipdn)
     1         ,((aaaa,la=1,lipdn),lo=1,lipdn)
      close(26)
c
c   coordinates for joint pdf between helicity and dissipation
c
      namfile='cojpdfdhlo.dat'
      open(26,file=namfile,form='unformatted')
      write(26)lipdn,lipdn
      write(26) ((alas(4,la),la=1,lipdn),lo=1,lipdn)
     1         ,((alorlo(1,lo),la=1,lipdn),lo=1,lipdn)
      close(26)
      nocpdf(1)=0
      do l=1,14
      do lla=1,lipdn
      do llo=1,lipdn
      ncpdw(l,lla,llo)=0.
            enddo
            enddo
      ntcpdw(l)=0
      nocpdw(l)=0
      enddo

            do np=1,4
         do ll=1,lipdn
      nllc(np,ll)=0
         enddo
      ntoc(np)=0
            enddo
            do np=26,39
         do ll=1,lipdn
      nllc(np,ll)=0
         enddo
      ntoc(np)=0
            enddo
      call outh(time)
c
c******************************************************
c    between the ******  the pdf of wall quantities are
c    calculated these have not benn considered in the 
c    book
c
c    read quantities at the lower wall
c
      nfill=90
      namfile='../fieldstati/lowalpdf'
      open(nfill,file=namfile,form='unformatted')
c
c    read quantities at the upper wall
c
      nfilu=89
      namfile='../fieldstati/upwalpdf'
      open(nfilu,file=namfile,form='unformatted')
      npq=1
      do l=1,39
      qavgv(l)=0.
      qrms(l)=0.
      qskew(l)=0.
      qflat(l)=0.
      qmapdf(l)=-100.
      qmipdf(l)=100.
      qmaflu(l)=-100
      qmiflu(l)=100.
      enddo
       quase(1)=1.
       quase(2)=2.
       quase(3)=4.
       quase(4)=6.
      do nse=1,5
            do l=1,4
      frrms(l,nse)=0.
      frskew(l,nse)=0.
      frflat(l,nse)=0.
            enddo
      enddo
      jc=1
      jp=2
      dv3x2l=(vmepo(3,jc))/(y2s(jc)-yp2(jc))
      dv1x2l=(vmepo(1,jc))/(y2s(jc)-yp2(jc))
      jc=n2m
      jm=n2m-1
      jp=n2
      dv3x2u=(-vmepo(3,jc))/(yp2(jp)-y2s(jc))
      dv1x2u=(-vmepo(1,jc))/(yp2(jp)-y2s(jc))
      write(6,*)' lower wall dv1x2,dv3x2 ',dv1x2l,dv3x2l
      write(6,*)' upper wall dv1x2,dv3x2 ',dv1x2u,dv3x2u
      
      do n=1,1000000
      read(nfill,end=1011)q1p,q3p,s12,s23,s13,prclw,dp1lw,dp3lw
c
c    itot =0 the total velocities were written and the mean is 
c    subctracted
c
      if(itot.eq.0) then
      q1p=q1p-dv3x2l
      s23=s23-dv3x2l*0.5
      q3p=q3p-dv1x2l
      s12=s12-dv1x2l*0.5
                    endif
      dq1x2=(2.*s12-q3p)*0.5
      dq3x2=(2.*s23+q1p)*0.5
      fr1wlw=dq1x2
      fr3wlw=dq3x2
      onglw=atan2(q3p,q1p)
      angolw=180./pi*onglw
      qcaplv(36,n)=q1p 
      qcaplv(37,n)=q3p 
      qcaplv(34,n)=angolw 
      read(nfilu)q1p,q3p,s12,s23,s13,prcup,dp1up,dp3up
      if(itot.eq.0) then
      q1p=q1p-dv3x2u
      s23=s23-dv3x2u*0.5
      q3p=q3p-dv1x2u
      s12=s12-dv1x2u*0.5
                    endif
c
c a bunch of quantities are stored in the array qcaplv
c
      dq1x2=(2.*s12-q3p)*0.5
      dq3x2=(2.*s23+q1p)*0.5
      fr1wup=dq1x2
      fr3wup=dq3x2
      ongup=atan2(q3p,q1p)
      angoup=180./pi*ongup
      qcaplv(35,n)=angoup 
      qcaplv(38,n)=q1p 
      qcaplv(39,n)=q3p 
      do3x2l=dp1lw*re
      do3x2u=dp1up*re
      do1x2l=-dp3lw*re
      do1x2u=-dp3up*re
      pnglw=atan2(do3x2l,do1x2l)
      pngup=atan2(do3x2u,do1x2u)
      anglw=180./pi*pnglw
      angup=180./pi*pngup
      qcaplv(1,n)=fr1wlw 
      qcaplv(2,n)=fr3wlw 
      qcaplv(3,n)=fr1wup 
      qcaplv(4,n)=fr3wup 
      qcaplv(26,n)=prclw 
      qcaplv(27,n)=prcup 
      qcaplv(28,n)=dp1lw 
      qcaplv(29,n)=dp1up 
      qcaplv(30,n)=dp3lw 
      qcaplv(31,n)=dp3up 
      qcaplv(32,n)=anglw 
      qcaplv(33,n)=angup 
      do lq=1,4
      qavgv(lq)=qavgv(lq)+qcaplv(lq,n)
      enddo
      do lq=26,39
      qavgv(lq)=qavgv(lq)+qcaplv(lq,n)
      enddo
      enddo
 1011 continue
      nsam=n-1
      write(6,*)' end read  nsam, nfill nfilu',nsam,nfill,nfilu
      write(18,*)' end read nsam, nfill nfilu',nsam,nfill,nfilu
      close(nfilu)
      close(nfill)
c
c   averages and rms of the quantities stored in qcaplv
c   are evaluated together with minima and maxima
c   and skewness and flatness
c
      do lq=1,4
      qavgv(lq)=qavgv(lq)/nsam
      qavck(lq)=0.
      enddo
      do lq=26,39
      qavgv(lq)=qavgv(lq)/nsam
      enddo
      do nl=1,nsam
      do l=26,39
      quav(l)=qcaplv(l,nl)
      qcaplv(l,nl)=quav(l)-qavgv(l)
      qmaflu(l)=max(qcaplv(l,nl),qmaflu(l))
      qmiflu(l)=min(qcaplv(l,nl),qmiflu(l))
      qrms(l)=qrms(l)+qcaplv(l,nl)**2
      qskew(l)=qskew(l)+qcaplv(l,nl)**3
      qflat(l)=qflat(l)+qcaplv(l,nl)**4
      enddo

      do l=1,4
      quav(l)=qcaplv(l,nl)
      qcaplv(l,nl)=quav(l)-qavgv(l)
      qmaflu(l)=max(qcaplv(l,nl),qmaflu(l))
      qmiflu(l)=min(qcaplv(l,nl),qmiflu(l))
      qrms(l)=qrms(l)+qcaplv(l,nl)**2
      qavck(l)=qavck(l)+qcaplv(l,nl)
      qskew(l)=qskew(l)+qcaplv(l,nl)**3
      qflat(l)=qflat(l)+qcaplv(l,nl)**4
      enddo
      enddo
      do l=1,4
      qrms(l)=sqrt(qrms(l)/nsam)
      qskew(l)=qskew(l)/nsam/qrms(l)**3
      qflat(l)=qflat(l)/nsam/qrms(l)**4
      write(6,134)l,qavgv(l),qmaflu(l),qmiflu(l),
     1            qrms(l),qskew(l),qflat(l)
      write(18,134)l,qavgv(l),qmaflu(l),qmiflu(l),
     1            qrms(l),qskew(l),qflat(l)
      enddo
      do l=26,39
      qrms(l)=sqrt(qrms(l)/nsam)
      qskew(l)=qskew(l)/nsam/qrms(l)**3
      qflat(l)=qflat(l)/nsam/qrms(l)**4
      write(6,134)l,qavgv(l),qmaflu(l),qmiflu(l),
     1            qrms(l),qskew(l),qflat(l)
      write(18,134)l,qavgv(l),qmaflu(l),qmiflu(l),
     1            qrms(l),qskew(l),qflat(l)
      enddo
           do l=1,4
      qlma=-1000.
      qlmi=1000.
      do nse=1,5
      frrms(l,nse)=0.
      frskew(l,nse)=0.
      frflat(l,nse)=0.
      nsafr(l,nse)=0
      enddo
           enddo
      do l=1,4
      do nl=1,nsam
      quapd=(qcaplv(l,nl))/qrms(l)
      aqua=abs(quapd)
      if(aqua.le.quase(1)) then
      frrms(l,1)=frrms(l,1)+(qcaplv(l,nl))**2
      nsafr(l,1)=nsafr(l,1)+1
c     frskew(l,1)=frskew(l,1)+quapd**3
c     frflat(l,1)=frflat(l,1)+quapd**4
                           endif
      if(aqua.le.quase(2).and.aqua.gt.quase(1)) then
      frrms(l,2)=frrms(l,2)+(qcaplv(l,nl))**2
      nsafr(l,2)=nsafr(l,2)+1
c     frskew(l,2)=frskew(l,2)+quapd**3
c     frflat(l,2)=frflat(l,2)+quapd**4
                           endif
      if(aqua.le.quase(3).and.aqua.gt.quase(2)) then
      frrms(l,3)=frrms(l,3)+(qcaplv(l,nl))**2
      nsafr(l,3)=nsafr(l,3)+1
c     frskew(l,3)=frskew(l,3)+quapd**3
c     frflat(l,3)=frflat(l,3)+quapd**4
                           endif
      if(aqua.le.quase(4).and.aqua.gt.quase(3)) then
      frrms(l,4)=frrms(l,4)+(qcaplv(l,nl))**2
      nsafr(l,4)=nsafr(l,4)+1
c     frskew(l,4)=frskew(l,4)+quapd**3
c     frflat(l,4)=frflat(l,4)+quapd**4
                           endif
      if(aqua.gt.quase(4)) then
      frrms(l,5)=frrms(l,5)+(qcaplv(l,nl))**2
      nsafr(l,5)=nsafr(l,5)+1
c     frskew(l,5)=frskew(l,5)+quapd**3
c     frflat(l,5)=frflat(l,5)+quapd**4
                           endif
      qlma=max(qlma,quapd)
      qlmi=min(qlmi,quapd)
c
c   fine do nl
c
      enddo
      allma(l)=qlma
      allmi(l)=qlmi
      antmm=allma(l)-allmi(l)
           do ll=1,lipdn
      alev(l,ll)=qmax*(ll-1-lipdh)/float(lipdh)
           enddo
           enddo
           do l=1,4
      qrmsck(l)=0.
      do nse=1,5
      qrmsck(l)=qrmsck(l)+frrms(l,nse)
      enddo
           enddo
      write(18,*)'  wall friction    events'
      write(6,*)'  wall friction    events check'
      do nse=1,5
           do l=1,4
      perfr(l)=frrms(l,nse)/qrmsck(l)
      evefr(l)=nsafr(l,nse)/float(nsam)
           enddo
      write(6,183) nse,(perfr(l),l=1,4),(evefr(l),l=1,4)
      write(18,183) nse,(perfr(l),l=1,4),(evefr(l),l=1,4)
 183  format(3x,i5,2x,4e15.5,3x,4e12.4)
      enddo
           do l=1,4
      perfr(l)=0.
      evefr(l)=0.
      do nse=1,5
      perfr(l)=perfr(l)+frrms(l,nse)/qrmsck(l)
      evefr(l)=evefr(l)+nsafr(l,nse)/float(nsam)
      enddo
           enddo

      write(6,184)(perfr(l),l=1,4),(evefr(l),l=1,4)
      write(18,184)(perfr(l),l=1,4),(evefr(l),l=1,4)
 184  format(8x,2x,4e15.5,3x,4e12.4)
           do l=26,39
      qlma=-1000.
      qlmi=1000.
      do nl=1,nsam
      if(l.ge.32.and.l.le.35) then
      quapd=(qcaplv(l,nl))
                              else
      quapd=(qcaplv(l,nl))/qrms(l)
                              endif
      qlma=max(qlma,quapd)
      qlmi=min(qlmi,quapd)
c
c   fine do nl
c
      enddo
      allma(l)=qlma
      allmi(l)=qlmi
      antmm=allma(l)-allmi(l)
      if(l.ge.32.and.l.le.35) then
      qmal=180.
                              else
      qmal=qmax
                              endif
           do ll=1,lipdn
      alev(l,ll)=qmal*(ll-1-lipdh)/float(lipdh)
           enddo
c
c   fine do l
c
           enddo
c
c    here the pdf are evaluated
c
      write(6,*)'qma 1 -4 ',(allma(l),l=1,4)
      write(6,*)'qma 26-39',(allma(l),l=26,39)
      write(6,*)'qmi 1 -4 ',(allmi(l),l=1,4)
      write(6,*)'qmi 26-39',(allmi(l),l=26,39)
      write(18,*)'qma 1 -4 ',(allma(l),l=1,4)
      write(18,*)'qma 26-39',(allma(l),l=26,39)
      write(18,*)'qmi 1 -4 ',(allmi(l),l=1,4)
      write(18,*)'qmi 26-39',(allmi(l),l=26,39)
                do nl=1,nsam
      do l=1,4 
      qpdf(l)=(qcaplv(l,nl))/qrms(l)
      if(abs(qpdf(l)).ge.qmax) then
      nou(l)=nou(l)+1
                               else
      all=lipdh*(qmax+qpdf(l))/qmax+1.
      ll=all
      if(ll.gt.mhpd.or.ll.le.0) then
       write(6,*)'stop',l,qpdf(l),all,qmax
       stop
                                 endif
      nllc(l,ll)=nllc(l,ll)+1
                               endif
      enddo
      do l=26,39 
      if(l.ge.32.and.l.le.35) then
      qpdf(l)=(qcaplv(l,nl))
      qmal=180.
                              else
      qpdf(l)=(qcaplv(l,nl))/qrms(l)
      qmal=qmax
                              endif
      if(abs(qpdf(l)).ge.qmal) then
      nou(l)=nou(l)+1
                               else
      all=lipdh*(qmal+qpdf(l))/qmal+1.
      ll=all
      if(ll.gt.mhpd.or.ll.le.0) then
       write(6,*)'stop',l,qpdf(l),all,qmal
       stop
                                 endif
      nllc(l,ll)=nllc(l,ll)+1
                               endif
      enddo
c
c   here the joint pdf are evaluated
c
      do lcp=1,14
      if(lcp.eq.1) then
c
c  p , omega_1  lower wall
c
      asc=(qcaplv(36,nl)+qavgv(36))/qrms(36)
      ord=(qcaplv(26,nl)+qavgv(26))/qrms(26)
      qlmax=qsmax
                 endif
      if(lcp.eq.2) then
c
c  p , omega_3  lower wall
c
      asc=(qcaplv(37,nl)+qavgv(37))/qrms(37)
      ord=(qcaplv(26,nl)+qavgv(26))/qrms(26)
      qlmax=qsmax
                 endif
      if(lcp.eq.3) then
c
c  dp/dx3=do1/dx2 , fr3wal  lower wall
c
      asc=(qcaplv(2,nl)+qavgv(2))/qrms(2)
      ord=(qcaplv(30,nl)+qavgv(30))/qrms(30)
      qlmax=qsmax
                 endif
      if(lcp.eq.4) then
c
c  dp/dx1=do3/dx2 , fr1wal  lower wall
c
      asc=(qcaplv(1,nl)+qavgv(1))/qrms(1)
      ord=(qcaplv(28,nl)+qavgv(28))/qrms(28)
      qlmax=qsmax
                 endif
      if(lcp.eq.5) then
c
c  dp/dx1=do3/dx2 , dp/dx3=do1/dx2 lower wall
c
      asc=(qcaplv(30,nl)+qavgv(30))/qrms(30)
      ord=(qcaplv(28,nl)+qavgv(28))/qrms(28)
      qlmax=qsmax
                 endif
      if(lcp.eq.6) then
c
c  p , omega_1  upper wall
c
      asc=(qcaplv(38,nl)+qavgv(38))/qrms(38)
      ord=(qcaplv(27,nl)+qavgv(27))/qrms(27)
      qlmax=qsmax
                 endif
      if(lcp.eq.7) then
c
c  p , omega_3  upper wall
c
      asc=(qcaplv(39,nl)+qavgv(39))/qrms(39)
      ord=(qcaplv(27,nl)+qavgv(27))/qrms(27)
      qlmax=qsmax
                 endif
      if(lcp.eq.8) then
c
c  dp/dx3=do1/dx2 , fr3wal  upper wall
c
      asc=(qcaplv(4,nl)+qavgv(4))/qrms(4)
      ord=(qcaplv(31,nl)+qavgv(31))/qrms(31)
      qlmax=qsmax
                 endif
      if(lcp.eq.9) then
c
c  dp/dx1=do3/dx2 , fr1wal  upper wall
c
      asc=(qcaplv(3,nl)+qavgv(3))/qrms(3)
      ord=(qcaplv(29,nl)+qavgv(29))/qrms(29)
      qlmax=qsmax
                 endif
      if(lcp.eq.10) then
c
c  dp/dx1=do3/dx2 , dp/dx3=do1/dx2 upper wall
c
      asc=(qcaplv(30,nl)+qavgv(30))/qrms(30)
      ord=(qcaplv(29,nl)+qavgv(29))/qrms(29)
      qlmax=qsmax
                 endif
      if(lcp.eq.12) then
c
c  fr3wal , fr1wal  lower wall
c
      asc=(qcaplv(1,nl)+qavgv(1))/qrms(1)
      ord=(qcaplv(2,nl)+qavgv(2))/qrms(2)
      qlmax=qsmax
                 endif
      if(lcp.eq.14) then
c
c  fr3wal , fr1wal  upper wall
c
      asc=(qcaplv(3,nl)+qavgv(3))/qrms(3)
      ord=(qcaplv(4,nl)+qavgv(4))/qrms(4)
      qlmax=qsmax
                 endif
      if(lcp.eq.11) then
c
c  omega_1 , omega_3  lower wall
c
      asc=(qcaplv(37,nl)+qavgv(37))/qrms(37)
      ord=(qcaplv(36,nl)+qavgv(36))/qrms(36)
      qlmax=qsmax
                 endif
      if(lcp.eq.13) then
c
c  omega_1 , omega_3  upper wall
c
      asc=(qcaplv(39,nl)+qavgv(39))/qrms(39)
      ord=(qcaplv(38,nl)+qavgv(38))/qrms(38)
      qlmax=qsmax
                 endif
      if(abs(asc).gt.qlmax.or.abs(ord).gt.qlmax) then
      nocpdw(lcp)=nocpdw(lcp)+1
                                     else
      ala=lipdh*(qlmax+asc)/qlmax+1.
      lla=ala
      alo=lipdh*(qlmax+ord)/qlmax+1.
      llo=alo
      if(lla.gt.mhpd.or.lla.le.0.or.llo.gt.mhpd.or.llo.le.0) then
       write(6,*)'stop wall  jpdf=',lcp,asc,ord
       stop
                                                             endif
      ncpdw(lcp,lla,llo)=ncpdw(lcp,lla,llo)+1
                                     endif
c
c  end do lcp for different quantities
c
c
             enddo


                 enddo
            do np=1,4 
                      do ll=1,lipdn
      ntoc(np)=ntoc(np)+nllc(np,ll)
                      enddo
      write(6,*)'lqua=',np,'  extrema  asc. pdf'
     1          ,allmi(np),allma(np),ntoc(np),nou(np)
      write(18,*)'lqua=',np,'  extrema  asc. pdf'
     1          ,allmi(np),allma(np),ntoc(np),nou(np)
            enddo
            do np=1,4
      pdft(np)=0.
            enddo
            do np=26,39 
                      do ll=1,lipdn
      ntoc(np)=ntoc(np)+nllc(np,ll)
                      enddo
      write(6,*)'lqua=',np,'  extrema  asc. pdf'
     1          ,allmi(np),allma(np),ntoc(np),nou(np)
      write(18,*)'lqua=',np,'  extrema  asc. pdf'
     1          ,allmi(np),allma(np),ntoc(np),nou(np)
            enddo
            do np=26,39
      pdft(np)=0.
            enddo
c******************************************************
c$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
c   the part of the code between the  $$$$$$$
c   account for the pdf inside the channel
c
c    read quantities at certain point in the channel
c
      npq=1
c
c   CALCULATION OF PDF IN THE INNER FIELD
c
      do jc=n2m,1,-1
      if(jc.eq.jprq(npq)) then
            do np=5,25    
         do ll=1,lipdn
      nllc(np,ll)=0
         enddo
      ntoc(np)=0
      nou(np)=0
            enddo
c
c   zero number for joint pdf
c
      do l=1,19
            do lla=1,lipdn
            do llo=1,lipdn
      ncpdf(l,lla,llo)=0.
            enddo
            enddo
      ntcpdf(l)=0
      nocpdf(l)=0
      cpdft(l)=0.
      enddo
      do l=1,9
            do lla=1,lipdn
            do llo=1,lipdn
      nvopdf(l,lla,llo)=0.
            enddo
            enddo
      ntcpvo(l)=0
      novopd(l)=0
      cpdtvo(l)=0.
      enddo
      do l=1,4
            do lla=1,lipdn
            do llo=1,lipdn
      ncpdfl(l,lla,llo)=0.
            enddo
            enddo
      ntcpdl(l)=0
      nocpdl(l)=0
      cpdftl(l)=0.
      enddo
      nfile=91+npq
      write(njpse,177) jc
  177 format(i3.3)
      namfile='../fieldstati/quapdf'//njpse
      open(nfile,file=namfile,form='unformatted')
      do l=5,25
      qrms(l)=0.
      qskew(l)=0.
      qflat(l)=0.
      qmapdf(l)=-100.
      qmipdf(l)=100.
      qmaflu(l)=-100
      qmiflu(l)=100.
      enddo
      jm=jc-1
      jp=jc+1
      dv3x2c=(vmepo(3,jc)-vmepo(3,jm))/(y2s(jc)-y2s(jm))
      dv3x2a=(vmepo(3,jp)-vmepo(3,jc))/(y2s(jp)-y2s(jc))
      dv3mx2=(dv3x2a+dv3x2c)*0.5
      dv1x2c=(vmepo(1,jc)-vmepo(1,jm))/(y2s(jc)-y2s(jm))
      dv1x2a=(vmepo(1,jp)-vmepo(1,jc))/(y2s(jp)-y2s(jc))
      dv1mx2=(dv1x2a+dv1x2c)*0.5
      dv2mx2=(vmepo(2,jp)-vmepo(2,jc))/(yp2(jp)-yp2(jc))
      write(6,*)' jc=',jc,'  dv1x2,dv3x2,dv2x2 ',dv1mx2,dv3mx2,dv2mx2
      do n=1,1000000                                                
      read(nfile,end=1012)v1p,v2p,v3p,q1p,q2p,q3p,
     1     s11,s22,s33,s12,s23,s13,pr
      if(itot.eq.0) then
      q1p=q1p-dv3mx2
      s23=s23-dv3mx2*0.5
      q3p=q3p-dv1mx2
      s12=s12-dv1mx2*0.5
      s22=s22-dv2mx2
      v1p=v1p-vmece(1,jc)
      v2p=v2p-vmece(2,jc)
      v3p=v3p-vmece(3,jc)
                    endif
      dq1x2=(2.*s12-q3p)*0.5
      dq2x1=(2.*s12+q3p)*0.5
      dq1x3=(2.*s13+q2p)*0.5
      dq3x1=(2.*s13-q2p)*0.5
      dq3x2=(2.*s23+q1p)*0.5
      dq2x3=(2.*s23-q1p)*0.5
      vmod=sqrt(v1p**2+v2p**2+v3p**2)
      omod=sqrt(q1p**2+q2p**2+q3p**2)
      qcaplv(5,n)=s11 
      qcaplv(6,n)=dq1x2 
      qcaplv(7,n)=dq1x3 
      qcaplv(8,n)=dq2x1 
      qcaplv(9,n)=s22 
      qcaplv(10,n)=dq2x3 
      qcaplv(11,n)=dq3x1 
      qcaplv(12,n)=dq3x2 
      qcaplv(13,n)=s33 
      qcaplv(14,n)=(v1p*q1p+v2p*q2p+v3p*q3p)/(vmod*omod)
      qcaplv(15,n)=(v2p*q3p-v3p*q2p)/(vmod*omod)
      qcaplv(16,n)=(v3p*q1p-v1p*q3p)/(vmod*omod)
      qcaplv(17,n)=(v1p*q2p-v2p*q1p)/(vmod*omod)
      enstro=(q1p*q1p+q2p*q2p+q3p*q3p)
      qcaplv(18,n)=enstro/4.
      dislo=(s11**2+s22**2+s33**2+
     1      2.*(s12**2+s13**2+s23**2))
      enspro=q1p**2*s11+q2p**2*s22+q3p**2*s33+
     1      2.*(q1p*q2p*s12+q2p*q3p*s23+q1p*q3p*s13)
      qcaplv(19,n)=dislo
      qcaplv(20,n)=enspro
      qcaplv(21,n)=pr
      qcaplv(22,n)=enstro/4.-dislo
      qcaplv(23,n)=q1p 
      qcaplv(24,n)=q2p
      qcaplv(25,n)=q3p
      qcaplv(40,n)=v1p 
      qcaplv(41,n)=v2p
      qcaplv(42,n)=v3p
                  do lq=5,25
      qavgv(lq)=qavgv(lq)+qcaplv(lq,n)
                  enddo
                  do lq=40,42
      qavgv(lq)=qavgv(lq)+qcaplv(lq,n)
                  enddo
      enddo
c
c   fine do n
c
 1012 continue
      nsam=n-1
      close(nfile)
      write(6,*)' end read nfile jc',nsam,nfile,jc
      write(18,*)' end read nfile jc',nsam,nfile,jc
                  do lq=5,25
      qavgv(lq)=qavgv(lq)/nsam
                  enddo
                  do lq=40,42
      qavgv(lq)=qavgv(lq)/nsam
                  enddo
      do nl=1,nsam
                  do l=5,25
      if(l.ge.14.and.l.le.17) then
                              else
      quav(l)=qcaplv(l,nl)
      qcaplv(l,nl)=quav(l)-qavgv(l)
                              endif
      qmaflu(l)=max(qcaplv(l,nl),qmaflu(l))
      qmiflu(l)=min(qcaplv(l,nl),qmiflu(l))
      qrms(l)=qrms(l)+qcaplv(l,nl)**2
      qskew(l)=qskew(l)+qcaplv(l,nl)**3
      qflat(l)=qflat(l)+qcaplv(l,nl)**4
                  enddo
                  do l=40,42
      qmaflu(l)=max(qcaplv(l,nl),qmaflu(l))
      qmiflu(l)=min(qcaplv(l,nl),qmiflu(l))
      qrms(l)=qrms(l)+qcaplv(l,nl)**2
      qskew(l)=qskew(l)+qcaplv(l,nl)**3
      qflat(l)=qflat(l)+qcaplv(l,nl)**4
                  enddo
c
c   fine do nl
c
      enddo
      do l=5,25
      qrms(l)=sqrt(qrms(l)/nsam)
      qskew(l)=qskew(l)/nsam/qrms(l)**3
      qflat(l)=qflat(l)/nsam/qrms(l)**4
      write(6,134)l,qavgv(l),qmaflu(l),qmiflu(l),
     1            qrms(l),qskew(l),qflat(l)
      write(18,134)l,qavgv(l),qmaflu(l),qmiflu(l),
     1            qrms(l),qskew(l),qflat(l)
  134 format(3x,i4,3x,8e15.5)
      enddo
      do l=40,42
      qrms(l)=sqrt(qrms(l)/nsam)
      qskew(l)=qskew(l)/nsam/qrms(l)**3
      qflat(l)=qflat(l)/nsam/qrms(l)**4
      write(6,134)l,qavgv(l),qmaflu(l),qmiflu(l),
     1            qrms(l),qskew(l),qflat(l)
      write(18,134)l,qavgv(l),qmaflu(l),qmiflu(l),
     1            qrms(l),qskew(l),qflat(l)
      enddo
           do l=5,25
      qlma=-1000.
      qlmi=1000.
      do nl=1,nsam
      if(l.ge.14.and.l.le.17) then
                              else
      quapd=(qcaplv(l,nl))/qrms(l)
      qlma=max(qlma,quapd)
      qlmi=min(qlmi,quapd)
                              endif

c
c   fine do nl
c
      enddo
      if(l.ge.14.and.l.le.17) then
           do ll=1,lipdn
      alev(l,ll)=(ll-1-lipdh)/float(lipdh)
           enddo
                              else
      allma(l)=qlma
      allmi(l)=qlmi
      antmm=allma(l)-allmi(l)
           do ll=1,lipdn
      alev(l,ll)=qmax*(ll-1-lipdh)/float(lipdh)
           enddo
                               endif
c
c   fine do l
c
           enddo
      do l=1,19
      ascma(l)=-1000.
      ordma(l)=-1000.
      ascmi(l)=+1000.
      ordmi(l)=+1000.
      enddo
      write(pjprc,88)jc
   88 format(i3.3)
                do nl=1,nsam
c
c  pdf  for the different quantities
c
      do l=5,25
      if(l.ge.14.and.l.le.17) then
      qpdf(l)=qcaplv(l,nl)
      all=lipdh*(1.+qpdf(l))+1.
      ll=all
      if(ll.gt.mhpd.or.ll.le.0) then
       write(6,*)'stop',l,qpdf(l),all,qmax
       stop
                                 endif
      nllc(l,ll)=nllc(l,ll)+1
                              else
      qpdf(l)=(qcaplv(l,nl))/qrms(l)
      if(abs(qpdf(l)).gt.qmax) then
      nou(l)=nou(l)+1
                               else
      all=lipdh*(qmax+qpdf(l))/qmax+1.
      ll=all
      if(ll.gt.mhpd.or.ll.le.0) then
       write(6,*)'stop',l,qpdf(l),all,qmax
       stop
                                 endif
      nllc(l,ll)=nllc(l,ll)+1
                               endif
                              endif
      enddo
c
c  joint pdf  of enstrophy and dissipation
c
      asc=(qcaplv(18,nl)+qavgv(18))/qrms(18)
      ord=(qcaplv(19,nl)+qavgv(19))/qrms(19)
      ascma(1)=max(asc,ascma(1))
      ordma(1)=max(ord,ordma(1))
      ascmi(1)=min(asc,ascmi(1))
      ordmi(1)=min(ord,ordmi(1))
      if(abs(asc).ge.qcmax.or.abs(ord).ge.qcmax) then
      nocpdf(1)=nocpdf(1)+1
                                     else
      ala=lipdn*asc/qcmax+1.
      lla=ala
      alo=lipdn*ord/qcmax+1.
      llo=alo
      if(lla.gt.mhpd.or.lla.le.0.or.llo.gt.mhpd.or.llo.le.0) then
       write(6,*)'stop dis,ens, jpdf=1',asc,ord,lla,llo
       stop
                                                             endif
      ncpdf(1,lla,llo)=ncpdf(1,lla,llo)+1
                                     endif
c
c  joint pdf  of vortex stretxching terms for omega_1
      do l=2,19
      if(l.eq.2) then
c
c  omega_1 du1x1
c
      asc=(qcaplv(5,nl)+qavgv(5))/qrms(5)
      ord=(qcaplv(23,nl)+qavgv(23))/qrms(23)
      qlmax=qcmax
                 endif
      if(l.eq.3) then
c
c  omega_2 du1x2
c
      asc=(qcaplv(6,nl)+qavgv(6))/qrms(6)
      ord=(qcaplv(24,nl)+qavgv(24))/qrms(24)
      qlmax=qcmax
                 endif
      if(l.eq.4) then
c
c  omega_3 du1x3
c
      asc=(qcaplv(7,nl)+qavgv(7))/qrms(7)
      ord=(qcaplv(25,nl)+qavgv(25))/qrms(25)
      qlmax=qcmax
                 endif
      if(l.eq.5) then
c
c  omega_1 du3x1
c
      asc=(qcaplv(11,nl)+qavgv(11))/qrms(11)
      ord=(qcaplv(23,nl)+qavgv(23))/qrms(23)
      qlmax=qcmax
                 endif
      if(l.eq.6) then
c
c  omega_2 du3x2
c
      asc=(qcaplv(12,nl)+qavgv(12))/qrms(12)
      ord=(qcaplv(24,nl)+qavgv(24))/qrms(24)
      qlmax=qcmax
                 endif
      if(l.eq.7) then
c
c  omega_3 du3x3
c
      asc=(qcaplv(13,nl)+qavgv(13))/qrms(13)
      ord=(qcaplv(25,nl)+qavgv(25))/qrms(25)
      qlmax=qcmax
                 endif
      if(l.eq.8) then
c
c  omega_1 du2x1
c
      asc=(qcaplv(8,nl)+qavgv(8))/qrms(8)
      ord=(qcaplv(23,nl)+qavgv(23))/qrms(23)
      qlmax=qcmax
                 endif
      if(l.eq.9) then
c
c  omega_2 du2x2
c
      asc=(qcaplv(9,nl)+qavgv(9))/qrms(9)
      ord=(qcaplv(24,nl)+qavgv(24))/qrms(24)
      qlmax=qcmax
                 endif
      if(l.eq.10) then
c
c  omega_3 du2x3
c
      asc=(qcaplv(10,nl)+qavgv(10))/qrms(10)
      ord=(qcaplv(25,nl)+qavgv(25))/qrms(25)
      qlmax=qcmax
                 endif
      if(l.eq.11) then
c
c  omega_1 du1x1
c
      asc=(qcaplv(5,nl)+qavgv(5))/qrms(5)
      om1=(qcaplv(23,nl)+qavgv(23))/qrms(23)
      ord=om1*om1
      qlmax=qsmax
                 endif
      if(l.eq.12) then
c
c  omega_2 du1x2
c
      asc=(qcaplv(6,nl)+qavgv(6))/qrms(6)
      om2=(qcaplv(24,nl)+qavgv(24))/qrms(24)
      om1=(qcaplv(23,nl)+qavgv(23))/qrms(23)
      ord=om1*om2
      qlmax=qsmax
                 endif
      if(l.eq.13) then
c
c  omega_3 du1x3
c
      asc=(qcaplv(7,nl)+qavgv(7))/qrms(7)
      om3=(qcaplv(25,nl)+qavgv(25))/qrms(25)
      om1=(qcaplv(23,nl)+qavgv(23))/qrms(23)
      ord=om1*om3
      qlmax=qsmax
                 endif
      if(l.eq.14) then
c
c  omega_1 du3x1
c
      asc=(qcaplv(11,nl)+qavgv(11))/qrms(11)
      om1=(qcaplv(23,nl)+qavgv(23))/qrms(23)
      om3=(qcaplv(25,nl)+qavgv(25))/qrms(25)
      ord=om1*om3
      qlmax=qsmax
                 endif
      if(l.eq.15) then
c
c  omega_2 du3x2
c
      asc=(qcaplv(12,nl)+qavgv(12))/qrms(12)
      om2=(qcaplv(24,nl)+qavgv(24))/qrms(24)
      om3=(qcaplv(25,nl)+qavgv(25))/qrms(25)
      ord=om2*om3
      qlmax=qsmax
                 endif
      if(l.eq.16) then
c
c  omega_3 du3x3
c
      asc=(qcaplv(13,nl)+qavgv(13))/qrms(13)
      om3=(qcaplv(25,nl)+qavgv(25))/qrms(25)
      ord=om3*om3
      qlmax=qsmax
                 endif
      if(l.eq.17) then
c
c  omega_1 du2x1
c
      asc=(qcaplv(8,nl)+qavgv(8))/qrms(8)
      om1=(qcaplv(23,nl)+qavgv(23))/qrms(23)
      om2=(qcaplv(24,nl)+qavgv(24))/qrms(24)
      ord=om2*om1
      qlmax=qsmax
                 endif
      if(l.eq.18) then
c
c  omega_2 du2x2
c
      asc=(qcaplv(9,nl)+qavgv(9))/qrms(9)
      om2=(qcaplv(24,nl)+qavgv(24))/qrms(24)
      ord=om2*om2
      qlmax=qsmax
                 endif
      if(l.eq.19) then
c
c  omega_3 du2x3
c
      asc=(qcaplv(10,nl)+qavgv(10))/qrms(10)
      om3=(qcaplv(25,nl)+qavgv(25))/qrms(25)
      om2=(qcaplv(24,nl)+qavgv(24))/qrms(24)
      ord=om2*om3
      qlmax=qsmax
                 endif
      ascma(l)=max(asc,ascma(l))
      ordma(l)=max(ord,ordma(l))
      ascmi(l)=min(asc,ascmi(l))
      ordmi(l)=min(ord,ordmi(l))
      if(abs(asc).ge.qlmax.or.abs(ord).ge.qlmax) then
      nocpdf(l)=nocpdf(l)+1
                                     else
      ala=lipdh*(qlmax+asc)/qlmax+1.
      lla=ala
      alo=lipdh*(qlmax+ord)/qlmax+1.
      llo=alo
      if(lla.gt.mhpd.or.lla.le.0.or.llo.gt.mhpd.or.llo.le.0) then
       write(6,*)'stop jpdf=',l,asc,ord
       stop
                                                             endif
      ncpdf(l,lla,llo)=ncpdf(l,lla,llo)+1
                                     endif
c
c  end do l for different quantities vortex stretching
c
c
             enddo
c
c  joint pdf  of dissipation/mean dissipation
c             and helicity density and Lamb vector
c
      ord=(qcaplv(19,nl)+qavgv(19))/qavgv(19)
      alo=lipdn*((alog(ord)/alog(10.)-alqcmi)/(alqcma-alqcmi))+1.
      llo=alo
      if(ord.le..1e-02.or.ord.ge.1.e+02) then
      do l=1,4
      nocpdl(l)=nocpdl(l)+1
      enddo
                                     else
      do l=1,4
      if(l.eq.1) then
c
c   cos vel vort
c
      asc=qcaplv(14,nl)
                 endif
      if(l.eq.2) then
      asc=qcaplv(15,nl)
                 endif
      if(l.eq.3) then
      asc=qcaplv(16,nl)
                 endif
      if(l.eq.4) then
      asc=qcaplv(17,nl)
                 endif
      ala=lipdh*(1.+asc)+1.
      lla=ala
      if(lla.gt.mhpd.or.lla.le.0.or.llo.gt.mhpd.or.llo.le.0) then
       write(6,*)'stop dis,angles, jpdf=',l,asc,ord
       stop
                                                             endif
      ncpdfl(l,lla,llo)=ncpdfl(l,lla,llo)+1
      enddo
                                     endif
c
c  joint pdf  of vorticity velocity correlations
c  
      do l=1,9
      if(l.eq.1) then
c
c  velocity_1  omega_1
c
      asc=(qcaplv(40,nl)+qavgv(40))/qrms(40)
      ord=(qcaplv(23,nl)+qavgv(23))/qrms(23)
      qlmax=qcmax
                 endif
      if(l.eq.2) then
c
c  velocity_1  omega_2
c
      asc=(qcaplv(40,nl)+qavgv(40))/qrms(40)
      ord=(qcaplv(24,nl)+qavgv(24))/qrms(24)
      qlmax=qcmax
                 endif
      if(l.eq.3) then
c
c  velocity_1  omega_3
c
      asc=(qcaplv(40,nl)+qavgv(40))/qrms(40)
      ord=(qcaplv(25,nl)+qavgv(25))/qrms(25)
      qlmax=qcmax
                 endif
      if(l.eq.4) then
c
c  velocity_2  omega_1
c
      asc=(qcaplv(41,nl)+qavgv(41))/qrms(41)
      ord=(qcaplv(23,nl)+qavgv(23))/qrms(23)
      qlmax=qcmax
                 endif
      if(l.eq.5) then
c
c  velocity_2  omega_2
c
      asc=(qcaplv(41,nl)+qavgv(41))/qrms(41)
      ord=(qcaplv(24,nl)+qavgv(24))/qrms(24)
      qlmax=qcmax
                 endif
      if(l.eq.6) then
c
c  velocity_2  omega_3
c
      asc=(qcaplv(41,nl)+qavgv(41))/qrms(41)
      ord=(qcaplv(25,nl)+qavgv(25))/qrms(25)
      qlmax=qcmax
                 endif
      if(l.eq.7) then
c
c  velocity_3  omega_1
c  omega_1 du2x1
c
      asc=(qcaplv(42,nl)+qavgv(42))/qrms(42)
      ord=(qcaplv(23,nl)+qavgv(23))/qrms(23)
      qlmax=qcmax
                 endif
      if(l.eq.8) then
c
c  velocity_3  omega_2
c
      asc=(qcaplv(42,nl)+qavgv(42))/qrms(42)
      ord=(qcaplv(24,nl)+qavgv(24))/qrms(24)
      qlmax=qcmax
                 endif
      if(l.eq.9) then
c
c  velocity_3  omega_3
c
      asc=(qcaplv(42,nl)+qavgv(42))/qrms(42)
      ord=(qcaplv(25,nl)+qavgv(25))/qrms(25)
      qlmax=qcmax
                 endif
      if(abs(asc).ge.qlmax.or.abs(ord).ge.qlmax) then
      novopd(l)=novopd(l)+1
                                     else
      ala=lipdh*(qlmax+asc)/qlmax+1.
      lla=ala
      alo=lipdh*(qlmax+ord)/qlmax+1.
      llo=alo
      if(lla.gt.mhpd.or.lla.le.0.or.llo.gt.mhpd.or.llo.le.0) then
       write(6,*)'stop jpdf=',l,asc,ord
       stop
                                    endif
      nvopdf(l,lla,llo)=nvopdf(l,lla,llo)+1
                                     endif
             enddo
c
c  end do l for velocity vorticity joint pdf
c
c

c
c   fine do nl for pdf
c
                 enddo
       write(18,136)(ascma(l),l=2,4),(ordma(l),l=2,4)
     1            ,(ascmi(l),l=2,4),(ordmi(l),l=2,4)
       write(18,137)(ascma(l),l=5,7),(ordma(l),l=5,7)
     1            ,(ascmi(l),l=5,7),(ordmi(l),l=5,7)
       write(18,138)(ascma(l),l=8,10),(ordma(l),l=8,10)
     1            ,(ascmi(l),l=8,10),(ordmi(l),l=8,10)
  138 format(2x,' j pdf max o2',14e9.2)
  137 format(2x,' j pdf max o3',14e9.2)
  136 format(2x,' j pdf max o1',14e9.2)
       write(18,236)(ascma(l),l=11,13),(ordma(l),l=11,13)
     1            ,(ascmi(l),l=11,13),(ordmi(l),l=11,13)
       write(18,237)(ascma(l),l=14,16),(ordma(l),l=14,16)
     1            ,(ascmi(l),l=14,16),(ordmi(l),l=14,16)
       write(18,238)(ascma(l),l=17,19),(ordma(l),l=17,19)
     1            ,(ascmi(l),l=17,19),(ordmi(l),l=17,19)
  238 format(2x,' j pdf max enpro2',14e9.2)
  237 format(2x,' j pdf max enpro3',14e9.2)
  236 format(2x,' j pdf max enpro1',14e9.2)
       write(6,*)' for jc=',jc,' enter in pdffin'
            do np=5,25
                      do ll=1,lipdn
      ntoc(np)=ntoc(np)+nllc(np,ll)
                      enddo
      write(18,*)'lqua=',np,'  extrema  asc. pdf'
     1          ,allmi(np),allma(np),ntoc(np),nou(np)
            enddo
            do np=5,25
      pdft(np)=0.
            enddo
      call pdffin(jc,npq)
c
c    endif do jc
c
            npq=npq+1
                          endif
c
c    fine do jc
c
      enddo
      stop                                                            
      end                                                               
c
c  ****************************** subrout pdffin **********************
c  write and calculates the pdf and the joint pdf
c
      subroutine pdffin(jc,npq)
      parameter (mqu=39,mhpd=201)
      parameter (mcqu=19,mcqw=14)
      common/pdf1/alev(mqu,mhpd),nllc(mqu,mhpd)
      common/pdf2/ntoz(mqu),qpdf(mqu),pdfvo(mqu)
      common/pdf3/nou(mqu),npou(mqu),ntoc(mqu)
      common/pdf4/pdft(mqu)
      common/pdf5/lipdf,lipdn,lipdh
      common/npdf/nqua
      common/cpdf1/alas(mcqu,mhpd),alor(mcqu,mhpd)
      common/cpdf2/ncpdf(mcqu,mhpd,mhpd),ntcpdf(mcqu),nocpdf(mqu)
      common/cpdf6/cpdft(mcqu),cpdfv(mcqu,mhpd,mhpd)
      common/cpdf3/ncpdw(mcqw,mhpd,mhpd),ntcpdw(mcqw),nocpdw(mcqw)
      common/cpdf9/cpdwt(mcqw),cpdwv(mcqw,mhpd,mhpd)
      parameter (mcqul=7)
      common/cpdf1l/alaslo(mcqul,mhpd),alorlo(mcqul,mhpd)
      common/cpdf2l/ncpdfl(mcqul,mhpd,mhpd),ntcpdl(mcqul),nocpdl(mqu)
      common/cpdf6l/cpdftl(mcqul),cpdfvl(mcqul,mhpd,mhpd)
      parameter (mcqvo=9)
      common/cpdf4/nvopdf(mcqvo,mhpd,mhpd),ntcpvo(mcqvo),novopd(mcqvo)
      common/cpdf8/cpdtvo(mcqvo),cpdfvo(mcqvo,mhpd,mhpd)
      dimension quadr(4,19)
      character*3 pjprc
      character*2 pqua
      character*60 filval
      write(pjprc,88)jc
   88 format(i3.3)
      aa=1
      ia=1
      if(npq.eq.1) then
                do l=1,4 
      nfile=50+l
      write(pqua,89) l
   89 format(i2.2)
      filval='pdf'//pqua//'sta'//pjprc//'.plo'
      open(nfile,file=filval)
      write(18,*)' open',nfile,'  as  ',filval
                enddo
                do l=26,39 
      nfile=50+l
      write(pqua,89) l
      filval='pdf'//pqua//'sta'//pjprc//'.plo'
      open(nfile,file=filval)
      write(18,*)' open',nfile,'  as  ',filval
                enddo
            do np=1,4 
      nfile=50+np
      write(6,*)' write on ',nfile,'   ntot(np',np,ntoc(np)
                 do ll=1,lipdn
      pdfvo(np)=nllc(np,ll)/float(ntoc(np))
      pdft(np)=pdft(np)+pdfvo(np)
      write(nfile,*)alev(np,ll),pdfvo(np)
  178 format(2x,e12.5,3x,6e14.5)
                  enddo
      close(nfile)
             enddo
      write(18,*)' total pdffor wall friction'
      write(18,198) (pdft(np),np=1,4)
            do np=26,39 
      nfile=50+np
      write(6,*)' write on ',nfile,'   ntot(np',np,ntoc(np)
                 do ll=1,lipdn
      pdfvo(np)=nllc(np,ll)/float(ntoc(np))
      pdft(np)=pdft(np)+pdfvo(np)
      write(nfile,*)alev(np,ll),pdfvo(np)
                  enddo
      close(nfile)
             enddo
      write(18,*)' total pdffor wall pressure'
      write(18,198) (pdft(np),np=26,39)
c
c    conditional pdf walls
c
                      do la=1,lipdn
                 do lo=1,lipdn
            do np=1,14
      ntcpdw(np)=ntcpdw(np)+ncpdw(np,la,lo)
            enddo
                 enddo
                      enddo
      write(6,*)' wall joint pdf',(ntcpdw(l),l=1,14)
      write(6,*)' out of range  ',(nocpdw(l),l=1,14)
      write(18,*)' wall joint pdf',(ntcpdw(l),l=1,14)
      write(18,*)'out of range   ',(nocpdw(l),l=1,14)
                 do la=1,lipdn
              do lo=1,lipdn
            do np=1,14
      cpdwv(np,la,lo)=ncpdw(np,la,lo)/float(ntcpdw(np))
      cpdwt(np)=cpdwt(np)+cpdwv(np,la,lo)
            enddo
              enddo
                  enddo
      write(18,*)' wall tot join pdf'
      write(18,179)(cpdwt(np),np=1,14)
      write(6,*)' wall tot join pdf'
      write(6,179)(cpdwt(np),np=1,14)
      filval='jpdflowal.dat'
      open(25,file=filval,form='unformatted')
      write(25)lipdn,lipdn,ia
      write(25)aa,aa,aa,aa
      write(25) 
     1           ((cpdwv(1,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdwv(2,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdwv(3,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdwv(4,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdwv(5,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdwv(11,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdwv(12,la,lo),la=1,lipdn),lo=1,lipdn)
      close(25)
      filval='jpdfupwal.dat'
      open(25,file=filval,form='unformatted')
      write(25)lipdn,lipdn,ia
      write(25)aa,aa,aa,aa
      write(25) 
     1           ((cpdwv(6,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdwv(7,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdwv(8,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdwv(9,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdwv(10,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdwv(13,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdwv(14,la,lo),la=1,lipdn),lo=1,lipdn)
      close(25)
                    endif
      do l=5,25
      nfile=50+l
      write(pqua,89) l
      filval='pdf'//pqua//'sta'//pjprc//'.plo'
      write(18,*)' open',nfile,'  as  ',filval
      open(nfile,file=filval)
      enddo
      nfile=50
            do np=5,25
      nfile=50+np
      write(6,*)' write on ',nfile,'   ntot(np',np,ntoc(np)
                 do ll=1,lipdn
      pdfvo(np)=nllc(np,ll)/float(ntoc(np))
      pdft(np)=pdft(np)+pdfvo(np)
      write(nfile,*)alev(np,ll),pdfvo(np)
                  enddo
      close(nfile)
                 enddo
      write(18,*)' total pdf at jc=',jc
      write(18,198) (pdft(np),np=5,25)
  198 format(2x,10e10.3)
c
c   Calculation of the coditional pdf
c
c     write(6,*) ' total condit. pdf'
      write(18,*) ' total condit. pdf'
                      do la=1,lipdn
                 do lo=1,lipdn
            do np=1,19
      ntcpdf(np)=ntcpdf(np)+ncpdf(np,la,lo)
            enddo
                 enddo
                      enddo
      write(6,*)' joint pdf good',(ntcpdf(l),l=1,10)
      write(6,*)' joint pdf out ',(nocpdf(l),l=1,10)
      write(18,*)' joint pdf good',(ntcpdf(l),l=1,10)
      write(18,*)' joint pdf out ',(nocpdf(l),l=1,10)
      write(18,*)' joint pdf',(ntcpdf(l),l=1,10),(nocpdf(l),l=1,10)
      write(6,*)' joint pdf Po good',(ntcpdf(l),l=11,19)
      write(6,*)' joint pdf Po out ',(nocpdf(l),l=11,19)
      write(18,*)' joint pdf Po good',(ntcpdf(l),l=11,19)
      write(18,*)' joint pdf Po out ',(nocpdf(l),l=11,19)
      do nu=1,4
            do np=1,19
      quadr(nu,np)=0.
            enddo
      enddo
      darea=1.
                 do la=1,lipdn
      ala=alas(2,la)
              do lo=1,lipdn
      alo=alor(2,lo)
            do np=1,19
      cpdfv(np,la,lo)=ncpdf(np,la,lo)/float(ntcpdf(np))
      cpdft(np)=cpdft(np)+cpdfv(np,la,lo)
      if(ala.gt.0.and.alo.lt.0) then
      quadr(4,np)=quadr(4,np)+cpdfv(np,la,lo)*darea
                                endif
      if(ala.lt.0.and.alo.lt.0) then
      quadr(3,np)=quadr(3,np)+cpdfv(np,la,lo)*darea
                                endif
      if(ala.lt.0.and.alo.gt.0) then
      quadr(2,np)=quadr(2,np)+cpdfv(np,la,lo)*darea
                                endif
      if(ala.gt.0.and.alo.gt.0) then
      quadr(1,np)=quadr(1,np)+cpdfv(np,la,lo)*darea
                                endif
            enddo
              enddo
                  enddo
      write(18,*)' at jc=',jc,'quadrant contribution vort stret'
      do np=1,19
      write(18,*)'np=',np,'   ',(quadr(l,np),l=1,4),cpdft(np)
      enddo
      write(18,*)' tot join pdf'
      write(18,179)(cpdft(np),np=1,19)
      write(6,*)' tot join pdf'
      write(6,179)(cpdft(np),np=1,19)
  179 format(3x,12e10.3)
      filval='jpdfoosij'//pjprc//'.dat'
      open(25,file=filval,form='unformatted')
      write(25)lipdn,lipdn
      write(25)aa,aa,aa,aa
      write(25) ((cpdfv(1,la,lo),la=1,lipdn),lo=1,lipdn)
      close(25)
      filval='jpdfvost1'//pjprc//'.dat'
      open(25,file=filval,form='unformatted')
      write(25)lipdn,lipdn,ia
      write(25)aa,aa,aa,aa
      write(25) ((cpdfv(2,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdfv(3,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdfv(4,la,lo),la=1,lipdn),lo=1,lipdn)
      close(25)
      filval='jpdfvost3'//pjprc//'.dat'
      open(25,file=filval,form='unformatted')
      write(25)lipdn,lipdn,ia
      write(25)aa,aa,aa,aa
      write(25) ((cpdfv(5,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdfv(6,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdfv(7,la,lo),la=1,lipdn),lo=1,lipdn)
      close(25)
      filval='jpdfvost2'//pjprc//'.dat'
      open(25,file=filval,form='unformatted')
      write(25)lipdn,lipdn,ia
      write(25)aa,aa,aa,aa
      write(25) ((cpdfv(8,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdfv(9,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdfv(10,la,lo),la=1,lipdn),lo=1,lipdn)
      filval='jpdfenpr1'//pjprc//'.dat'
      open(25,file=filval,form='unformatted')
      write(25)lipdn,lipdn,ia
      write(25)aa,aa,aa,aa
      write(25) ((cpdfv(11,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdfv(12,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdfv(13,la,lo),la=1,lipdn),lo=1,lipdn)
      close(25)
      filval='jpdfenpr3'//pjprc//'.dat'
      open(25,file=filval,form='unformatted')
      write(25)lipdn,lipdn,ia
      write(25)aa,aa,aa,aa
      write(25) 
     1           ((cpdfv(14,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdfv(15,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdfv(16,la,lo),la=1,lipdn),lo=1,lipdn)
      close(25)
      filval='jpdfenpr2'//pjprc//'.dat'
      open(25,file=filval,form='unformatted')
      write(25)lipdn,lipdn,ia
      write(25)aa,aa,aa,aa
      write(25) 
     1           ((cpdfv(17,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdfv(18,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdfv(19,la,lo),la=1,lipdn),lo=1,lipdn)
      close(25)
                      do la=1,lipdn
                 do lo=1,lipdn
            do np=1,4
      ntcpdl(np)=ntcpdl(np)+ncpdfl(np,la,lo)
            enddo
                 enddo
                      enddo
                 do la=1,lipdn
              do lo=1,lipdn
            do np=1,4
      cpdfvl(np,la,lo)=ncpdfl(np,la,lo)/float(ntcpdl(np))
      cpdftl(np)=cpdftl(np)+cpdfvl(np,la,lo)
            enddo
              enddo
                  enddo
      filval='jpdfdihe'//pjprc//'.dat'
      open(25,file=filval,form='unformatted')
      write(25)lipdn,lipdn
      write(25)aa,aa,aa,aa
      write(25) 
     1           ((cpdfvl(1,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdfvl(2,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdfvl(3,la,lo),la=1,lipdn),lo=1,lipdn)
     1           ,((cpdfvl(4,la,lo),la=1,lipdn),lo=1,lipdn)
      close(25)
c
c   Calculation of the coditional pdf vorticity-velocity
c
c     write(6,*) ' total condit. pdf'
      write(18,*) ' total condit. pdf'
                      do la=1,lipdn
                 do lo=1,lipdn
            do np=1,9
      ntcpvo(np)=ntcpvo(np)+nvopdf(np,la,lo)
            enddo
                 enddo
                      enddo
      do nu=1,4
            do np=1,9
      quadr(nu,np)=0.
            enddo
      enddo
      darea=1.
                 do la=1,lipdn
      ala=alas(2,la)
              do lo=1,lipdn
      alo=alor(2,lo)
            do np=1,9
      cpdfvo(np,la,lo)=nvopdf(np,la,lo)/float(ntcpvo(np))
      cpdtvo(np)=cpdtvo(np)+cpdfvo(np,la,lo)
      if(ala.gt.0.and.alo.lt.0) then
      quadr(4,np)=quadr(4,np)+cpdfvo(np,la,lo)*darea
                                endif
      if(ala.lt.0.and.alo.lt.0) then
      quadr(3,np)=quadr(3,np)+cpdfvo(np,la,lo)*darea
                                endif
      if(ala.lt.0.and.alo.gt.0) then
      quadr(2,np)=quadr(2,np)+cpdfvo(np,la,lo)*darea
                                endif
      if(ala.gt.0.and.alo.gt.0) then
      quadr(1,np)=quadr(1,np)+cpdfvo(np,la,lo)*darea
                                endif
            enddo
              enddo
                  enddo
      write(18,*)' at jc=',jc,'quadrant contribution vort vel'
      do np=1,9
      write(18,*)'np=',np,'   ',(quadr(l,np),l=1,4),cpdtvo(np)
      enddo
      filval='jpdfvo1'//pjprc//'.dat'
      open(25,file=filval,form='unformatted')
      write(25)lipdn,lipdn,ia
      write(25)aa,aa,aa,aa
      write(25) ((cpdfvo(1,la,lo),la=1,lipdn),lo=1,lipdn)
     1         ,((cpdfvo(2,la,lo),la=1,lipdn),lo=1,lipdn)
     1         ,((cpdfvo(3,la,lo),la=1,lipdn),lo=1,lipdn)
      close(25)
      filval='jpdfvo2'//pjprc//'.dat'
      open(25,file=filval,form='unformatted')
      write(25)lipdn,lipdn,ia
      write(25)aa,aa,aa,aa
      write(25) ((cpdfvo(4,la,lo),la=1,lipdn),lo=1,lipdn)
     1         ,((cpdfvo(5,la,lo),la=1,lipdn),lo=1,lipdn)
     1         ,((cpdfvo(6,la,lo),la=1,lipdn),lo=1,lipdn)
      close(25)
      filval='jpdfvo3'//pjprc//'.dat'
      open(25,file=filval,form='unformatted')
      write(25)lipdn,lipdn,ia
      write(25)aa,aa,aa,aa
      write(25) ((cpdfvo(7,la,lo),la=1,lipdn),lo=1,lipdn)
     1         ,((cpdfvo(8,la,lo),la=1,lipdn),lo=1,lipdn)
     1         ,((cpdfvo(9,la,lo),la=1,lipdn),lo=1,lipdn)
      close(25)
      return
      end
c************************************************************************
c                                                                       *
c    *****   subro outh   ********************************              *
c                                                                       *
c************************************************************************
      subroutine outh(time)
      parameter (m1=65,m3=257,mfile=50,m2=151)
      character*60 filpvp,filvv,filuvt,filvwt,filvtv,filvtd,filvtn
      character*60 fivevo,filhel,filpro,filqst,filvmt,filvcock
      character*60 filpgr,filqno
      character*60 filcnw,filcnr,filth,filvm,filpo,filen
      character*60 filet,filer,filez,filed,filev
      character*60 filqm,filve,filvo,filvn,filvt,filvmp
      character*60 filns,filts,filsk,filfl,filuvp,filnsp
      character*60 filvsp,filnu,filba1,filba2,filba3
      character*60 filvtb,filval,filpsc,filpco,filpsp
      common/nn2/n2,n2m
      common/quaprs/y2s(m2),tstppl(6,m2),sijsij(m2),enstr(m2),enpro(m2)
     1,pvp(6,m2),tostpl(6,m2),vmece(6,m2),pmece(m2),vomce(6,m2)
     1,vstp(6,m2),tstp(6,m2),skew(6,m2),flat(6,m2),dvtv(6,m2)
     1,vtv(6,m2),vvo(6,m2),hel(6,m2),dstr(6,m2),vcom(6,m2)
      common/quaprc/yp2(m2),vmepo(6,m2),vompo(6,m2)
      character*3 njpse
      character*4 pntim
      itim=nint(time)
      write(pntim,77) itim
   77 format(i4.4)
      filve='../fieldstati/oupivm.'//pntim
      filuvp='../fieldstati/oupiuvp.'//pntim
      filuvt='../fieldstati/oupiuvt.'//pntim
      filvwt='../fieldstati/oupivwt.'//pntim
      filvmt='../fieldstati/oupiens.'//pntim
      filnsp='../fieldstati/oupinsp.'//pntim
      filvtb='../fieldstati/oupivtb.'//pntim
      filpvp='../fieldstati/oupipvp.'//pntim
      filvsp='../fieldstati/oupivsp.'//pntim
      filvmp='../fieldstati/oupivmp.'//pntim
      filvtn='../fieldstati/oupivtn.'//pntim
      filvtv='../fieldstati/oupivtv.'//pntim
      filvtd='../fieldstati/oupivtd.'//pntim
      filvcock='../fieldstati/oupivcock.'//pntim
      filnu='../fieldstati/oupinu.'//pntim
      filvo='../fieldstati/oupivo.'//pntim
      filvn='../fieldstati/oupivn.'//pntim
      filvt='../fieldstati/oupivt.'//pntim
      filvv='../fieldstati/oupivv.'//pntim
      filns='../fieldstati/oupins.'//pntim
      filts='../fieldstati/oupits.'//pntim
      filsk='../fieldstati/oupisf.'//pntim
      filfl='../fieldstati/oupifl.'//pntim
      filpro='../fieldstati/oupipr1.'//pntim
      filqst='../fieldstati/oupiqst.'//pntim
      filqno='../fieldstati/oupiqno.'//pntim
      filpgr='../fieldstati/oupipgr.'//pntim
      filhel='../fieldstati/oupihel.'//pntim
      fivevo='../fieldstati/oupivev.'//pntim
      open(91,file=fivevo)
      open(92,file=filpro)
      open(93,file=filhel)
      open(94,file=filqst)
      open(96,file=filqno)
      open(95,file=filvcock)
      open(116,file=filuvp)
      open(119,file=filvtb)
      open(129,file=filvmt)
      open(120,file=filpvp)
      open(114,file=filvwt)
      open(48,file=filvtv)
      open(47,file=filvtd)
      open(45,file=filvtn)
      open(51,file=filve)
      open(52,file=filvo)
      open(53,file=filvn)
      open(54,file=filvt)
      open(57,file=filsk)
      open(58,file=filfl)
      filns='../fieldstati/oupins.'//pntim
      open(55,file=filns)
      filts='../fieldstati/oupits.'//pntim
      open(56,file=filts)
  612 format(1x,e12.4,2x,9(1x,e12.5))
      n2mh=n2m/2+1
      n2m2=n2m/2
      do  j=1,n2
      read(96,612)yd,vmepo(2,j),vompo(1,j),vompo(3,j)
      if(j.le.n2mh) then
      yp2(j)=-1+yd
                    else
      yp2(j)=1.-yd
                    endif
      enddo
      do  j=1,n2m
      read(94,612)yd,vmepo(1,j),vmepo(3,j),vompo(2,j)
      read(116,612)y2ss,(tstppl(l,j),l=4,6)
      read(129,612)y2ss,sijsij(j),enstr(j),enpro(j)
      read(120,612)y2ss,(pvp(l,j),l=1,4)
      read(114,612)y2ss,(tostpl(l,j),l=1,3)
      read(51,612)y2ss,(vmece(l,j),l=1,3),pmece(j)   
      read(52,612)y2ss,(vomce(l,j),l=1,3)
      read(53,612)y2ss,(vstp(l,j),l=1,3)
      read(54,612)y2ss,(vstp(l,j),l=4,6)
      read(55,612)y2ss,(tstp(l,j),l=1,3)
      read(56,612)y2ss,(tstp(l,j),l=4,6)
      read(57,612)y2ss,(skew(l,j),l=1,4)
      read(58,612)y2ss,(flat(l,j),l=1,4)
      read(47,612)y2ss,(dvtv(l,j),l=1,5)
      read(45,612)y2ss,(vtv(l,j),l=1,5)
      read(91,612)y2ss,(vvo(l,j),l=1,6)
      read(93,612)y2ss,(hel(l,j),l=1,3)
      read(95,612)y2ss,dstr(1,j),vcom(1,j),dstr(2,j),vcom(2,j),
     1                   dstr(3,j),vcom(3,j)
      if(j.le.n2m2) then
      y2s(j)=-1+yd
                    else
      y2s(j)=1.-yd
                    endif
      enddo
      close(91)
      close(92)
      close(93)
      close(94)
      close(96)
      close(95)
      close(116)
      close(119)
      close(129)
      close(120)
      close(114)
      close(48)
      close(47)
      close(45)
      close(51)
      close(52)
      close(53)
      close(54)
      close(57)
      close(58)
      close(55)
      close(56)
      return
      end




